// Заглушки — потом заменяются на реальные запросы к API

export const MOCK_CATEGORIES = [
  { id: 1, slug: 'all',         name: 'Все книги' },
  { id: 2, slug: 'fiction',     name: 'Художественная' },
  { id: 3, slug: 'non-fiction', name: 'Нон-фикшн' },
  { id: 4, slug: 'business',    name: 'Бизнес' },
  { id: 5, slug: 'psychology',  name: 'Психология' },
  { id: 6, slug: 'children',    name: 'Детям' },
  { id: 7, slug: 'science',     name: 'Наука' },
  { id: 8, slug: 'history',     name: 'История' },
  { id: 9, slug: 'art',         name: 'Искусство' },
  { id: 10, slug: 'comics',     name: 'Комиксы' },
]

export const MOCK_BANNERS = [
  {
    id: 1,
    title: 'Книги, которые меняют мышление',
    subtitle: 'Нон-фикшн бестселлеры со скидкой до 30%',
    buttonText: 'Смотреть подборку',
    bgColor: '#0D7377',
    image: null,
  },
  {
    id: 2,
    title: 'Новинки апреля',
    subtitle: 'Первыми читайте то, о чём будут говорить все',
    buttonText: 'Новинки',
    bgColor: '#1a3a4a',
    image: null,
  },
  {
    id: 3,
    title: 'Детская библиотека',
    subtitle: 'Книги для детей от 0 до 16 лет',
    buttonText: 'В раздел',
    bgColor: '#2d5a3d',
    image: null,
  },
]

export const MOCK_BOOKS = [
  {
    id: 1,
    title: 'Атомные привычки',
    author: 'Джеймс Клир',
    genre: 'Нон-фикшн',
    price: 890,
    oldPrice: 1190,
    rating: 4.8,
    reviewCount: 2341,
    cover: 'https://covers.openlibrary.org/b/isbn/9780735211292-L.jpg',
    isNew: false,
    isPopular: true,
    inStock: true,
    categorySlug: 'non-fiction',
  },
  {
    id: 2,
    title: 'Мастер и Маргарита',
    author: 'Михаил Булгаков',
    genre: 'Художественная',
    price: 650,
    oldPrice: null,
    rating: 4.9,
    reviewCount: 5120,
    cover: 'https://covers.openlibrary.org/b/isbn/9780679600657-L.jpg',
    isNew: false,
    isPopular: true,
    inStock: true,
    categorySlug: 'fiction',
  },
  {
    id: 3,
    title: 'Думай медленно... Решай быстро',
    author: 'Дэниел Канеман',
    genre: 'Психология',
    price: 990,
    oldPrice: 1290,
    rating: 4.7,
    reviewCount: 1876,
    cover: 'https://covers.openlibrary.org/b/isbn/9780374533557-L.jpg',
    isNew: false,
    isPopular: true,
    inStock: true,
    categorySlug: 'psychology',
  },
  {
    id: 4,
    title: 'Сапиенс. Краткая история человечества',
    author: 'Юваль Ной Харари',
    genre: 'История',
    price: 1100,
    oldPrice: null,
    rating: 4.6,
    reviewCount: 3200,
    cover: 'https://covers.openlibrary.org/b/isbn/9780062316097-L.jpg',
    isNew: false,
    isPopular: true,
    inStock: true,
    categorySlug: 'history',
  },
  {
    id: 5,
    title: 'Игра в классики',
    author: 'Хулио Кортасар',
    genre: 'Художественная',
    price: 720,
    oldPrice: null,
    rating: 4.5,
    reviewCount: 890,
    cover: 'https://covers.openlibrary.org/b/isbn/9780394728285-L.jpg',
    isNew: true,
    isPopular: false,
    inStock: true,
    categorySlug: 'fiction',
  },
  {
    id: 6,
    title: 'Краткие ответы на большие вопросы',
    author: 'Стивен Хокинг',
    genre: 'Наука',
    price: 780,
    oldPrice: 950,
    rating: 4.8,
    reviewCount: 1540,
    cover: 'https://covers.openlibrary.org/b/isbn/9781984819192-L.jpg',
    isNew: false,
    isPopular: false,
    inStock: true,
    categorySlug: 'science',
  },
  {
    id: 7,
    title: 'От нуля к единице',
    author: 'Питер Тиль',
    genre: 'Бизнес',
    price: 860,
    oldPrice: null,
    rating: 4.6,
    reviewCount: 2100,
    cover: 'https://covers.openlibrary.org/b/isbn/9780804139021-L.jpg',
    isNew: false,
    isPopular: true,
    inStock: false,
    categorySlug: 'business',
  },
  {
    id: 8,
    title: 'Преступление и наказание',
    author: 'Фёдор Достоевский',
    genre: 'Художественная',
    price: 590,
    oldPrice: null,
    rating: 4.7,
    reviewCount: 4300,
    cover: 'https://covers.openlibrary.org/b/isbn/9780486415871-L.jpg',
    isNew: false,
    isPopular: false,
    inStock: true,
    categorySlug: 'fiction',
  },
  {
    id: 9,
    title: '7 навыков высокоэффективных людей',
    author: 'Стивен Кови',
    genre: 'Бизнес',
    price: 950,
    oldPrice: 1200,
    rating: 4.5,
    reviewCount: 1980,
    cover: 'https://covers.openlibrary.org/b/isbn/9780743269513-L.jpg',
    isNew: false,
    isPopular: false,
    inStock: true,
    categorySlug: 'business',
  },
  {
    id: 10,
    title: 'Тонкое искусство пофигизма',
    author: 'Марк Мэнсон',
    genre: 'Психология',
    price: 790,
    oldPrice: 990,
    rating: 4.3,
    reviewCount: 3400,
    cover: 'https://covers.openlibrary.org/b/isbn/9780062457714-L.jpg',
    isNew: false,
    isPopular: false,
    inStock: true,
    categorySlug: 'psychology',
  },
  {
    id: 11,
    title: 'Малыш и Карлсон',
    author: 'Астрид Линдгрен',
    genre: 'Детям',
    price: 450,
    oldPrice: null,
    rating: 4.9,
    reviewCount: 6700,
    cover: 'https://covers.openlibrary.org/b/isbn/9780140309799-L.jpg',
    isNew: false,
    isPopular: true,
    inStock: true,
    categorySlug: 'children',
  },
  {
    id: 12,
    title: 'Чёрный лебедь',
    author: 'Нассим Талеб',
    genre: 'Нон-фикшн',
    price: 1050,
    oldPrice: null,
    rating: 4.6,
    reviewCount: 1230,
    cover: 'https://covers.openlibrary.org/b/isbn/9781400063512-L.jpg',
    isNew: true,
    isPopular: false,
    inStock: true,
    categorySlug: 'non-fiction',
  },
]

export const SORT_OPTIONS = [
  { value: 'popular',   label: 'Популярные' },
  { value: 'new',       label: 'Новинки' },
  { value: 'price_asc', label: 'Цена: по возрастанию' },
  { value: 'price_desc',label: 'Цена: по убыванию' },
  { value: 'rating',    label: 'По рейтингу' },
]
